mv ttGamma_Dilept_rwgt_customizecards.dat ttGamma_Dilept_restrict_rwgt_customizecards.dat
mv ttGamma_Dilept_rwgt_proc_card.dat ttGamma_Dilept_restrict_rwgt_proc_card.dat
mv ttGamma_Dilept_rwgt_reweight_card.dat ttGamma_Dilept_restrict_rwgt_reweight_card.dat
mv ttGamma_Dilept_rwgt_reweight_card.pkl ttGamma_Dilept_restrict_rwgt_reweight_card.pkl
mv ttGamma_Dilept_rwgt_run_card.dat ttGamma_Dilept_restrict_rwgt_run_card.dat
