mv st_tch_4f_ckm_top_13TeV_UL_powheg_madspin_customizecards.dat stg_tch_rwgt_customizecards.dat
mv st_tch_4f_ckm_top_13TeV_UL_powheg_madspin_madspin_card.dat stg_tch_rwgt_madspin_card.dat
mv st_tch_4f_ckm_top_13TeV_UL_powheg_madspin_proc_card.dat stg_tch_rwgt_proc_card.dat
mv st_tch_4f_ckm_top_13TeV_UL_powheg_madspin_run_card.dat stg_tch_rwgt_run_card.dat
mv ttGamma_Dilept_restrict_rwgt_extramodels.dat stg_tch_rwgt_extramodels.dat
mv ttGamma_Dilept_restrict_rwgt_reweight_card.dat stg_tch_rwgt_reweight_card.dat
mv ttGamma_Dilept_restrict_rwgt_reweight_card.pkl stg_tch_rwgt_reweight_card.pkl
