mv tt0123j_5f_ckm_LO_MLM_customizecards.dat tt0123j_rwgt_customizecards.dat
mv tt0123j_5f_ckm_LO_MLM_madspin_card.dat tt0123j_rwgt_madspin_card.dat
mv tt0123j_5f_ckm_LO_MLM_proc_card.dat tt0123j_rwgt_proc_card.dat
mv tt0123j_5f_ckm_LO_MLM_run_card.dat tt0123j_rwgt_run_card.dat
mv ttGamma_Dilept_restrict_rwgt_extramodels.dat tt0123j_rwgt_extramodels.dat
mv ttGamma_Dilept_restrict_rwgt_reweight_card.dat tt0123j_rwgt_reweight_card.dat
mv ttGamma_Dilept_restrict_rwgt_reweight_card.pkl tt0123j_rwgt_reweight_card.pkl
