mv tt0123j_rwgt_customizecards.dat tt01j_rwgt_customizecards.dat
mv tt0123j_rwgt_extramodels.dat tt01j_rwgt_extramodels.dat
mv tt0123j_rwgt_madspin_card.dat tt01j_rwgt_madspin_card.dat
mv tt0123j_rwgt_proc_card.dat tt01j_rwgt_proc_card.dat
mv tt0123j_rwgt_restrict_custom.dat tt01j_rwgt_restrict_custom.dat
mv tt0123j_rwgt_reweight_card.dat tt01j_rwgt_reweight_card.dat
mv tt0123j_rwgt_reweight_card.pkl tt01j_rwgt_reweight_card.pkl
mv tt0123j_rwgt_run_card.dat tt01j_rwgt_run_card.dat
