mv st_sch_rwgt_customizecards.dat stg_sch_rwgt_customizecards.dat
mv st_sch_rwgt_extramodels.dat stg_sch_rwgt_extramodels.dat
mv st_sch_rwgt_madspin_card.dat stg_sch_rwgt_madspin_card.dat
mv st_sch_rwgt_proc_card.dat stg_sch_rwgt_proc_card.dat
mv st_sch_rwgt_reweight_card.dat stg_sch_rwgt_reweight_card.dat
mv st_sch_rwgt_reweight_card.pkl stg_sch_rwgt_reweight_card.pkl
mv st_sch_rwgt_run_card.dat stg_sch_rwgt_run_card.dat

